### ISSUE TITLE
How to use models?

### ISSUE THREAD

**Issue by rzschoch** [fenixkim/KirbySections#1]
Thank you so much for your plugin.

Could you please give an example on how it is possible to make use of Kirbys template models? I tried the documented way but struggled in giving the correct name to the Model Class. According to the documentation the class name has to correspond with the template name:

"The class name corresponds with the name of the template and text file. So if your text file is called project.txt Kirby will look for a project.php model file with a ProjectPage class." (http://getkirby.com/docs/templates/models)

As a prefixed underscore is not allowed for a class, how do you use the model and controller feature?

Thanks a lot,
René

**Comment by fenixkim** [comment]
Hey @rzschoch, 

Thanks for your comment, I realized I had a poor support for the use of Models for this pluging, I fixed a little bit the code, please upgrade to the most recent version.

Underscores are not a problem for Models, Kirby automatically searches for the name ignoring: dots, dashes and underscores :) then your files would look like this:

Model (`models/_mysection.php`):

```
class MySectionPage extends Section {
  public function foo() {
    return "Var from the Model";
  }
}
```

Note that the name of the `Section` should still finish in `Page`, and must be a subclass of `Section` instead of `Page`

Controller (`controllers/_mysection.php`):

```
return function($site, $pages, $page) {

  // Avoid direct link to this section if needed
  Sections::avoidDirectLink($page);

  $foo = "Var from the Controller";

  return compact("foo");
};
```

Template (`templates/_mysection.php`):

```
<section>

  <!-- Habitual fields -->
  <p><?php echo $page->title() ?></p>

  <!-- From controller -->
  <p><?php echo $foo ?></p>

  <!-- From model -->
  <p><?php echo $page->foo() ?></p>

</section>
```

I hope it is clearer now, any contribution is welcome

**Comment by rzschoch** [comment]
Hey @fenixkim,

thanks a lot for your help – it works :)

Have a great day,
René
